core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include('users.urls')),
    path("", include('home.urls'), name="home"),
    path('todo/', include("todo.urls"), name="todo"),
]

home/urls.py
from django.urls import path
from . import views


app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

todo/urls.py
from django.urls import path
from . import views


app_name = 'todo'
urlpatterns = [
    path("my_todos/", views.TodoListView.as_view(), name="my_todos"),
    path("todo_details/<int:pk>/", views.TodoDetailView.as_view(), name="todo_details"),
    path("<int:pk>/update/", views.TodoUpdateView.as_view(), name="todo_update"),
    path("create/", views.TodoCreateView.as_view(), name="todo_create"),
    path('<int:pk>/delete/', views.TodoDeleteView.as_view(), name='todo_delete'),
    path("<int:pk>/done/", views.TodoDoneView.as_view(), name='todo_done'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView


app_name = 'users'
urlpatterns = [
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('logout/', LogoutView.as_view(next_page="home:home"), name='logout'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.views.generic import TemplateView
from todo.models import Todo


class HomeView(TemplateView):
    """
    A simple view for the home page
    """
    template_name = 'home/home.html'


templates/home/home.html
{% extends 'base.html' %}
{% load static %}
    {% block head %}
    	<title>Todo App</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'home/css/styles.css' %}">
    {% endblock head %}

{% block content %}


    <div class="container">

        {% if request.user.is_authenticated %}
            <h1> Welcome dear {{ request.user.username }}</h1>
            <a href="{% url 'users:logout' %}" class="link-danger">logout</a>
        {% else %}
            <h1>Welcome to Todo App</h1>
            <a href="{% url 'users:signup' %}" class="link-info">signup</a><hr/>
            <a href="{% url 'users:login' %}" class="link-info">login</a>
        {% endif %}
        <p>A simple and efficient way to manage your tasks.</p>
    {% if request.user.is_authenticated %}
    	<a href="{% url 'todo:my_todos' %}" class="link-body-emphasis">My tasks</a><hr><br>
        <a href="{% url 'todo:todo_create' %}" class="link-body-emphasis">add new task</a><hr><br>
    {% endif %}


    </div>

{% endblock content %}