core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include('users.urls')),
    path("", include('home.urls'), name="home"),
    path('todo/', include("todo.urls"), name="todo"),
]

todo/urls.py
from django.urls import path
from . import views


app_name = 'todo'
urlpatterns = [
    path("my_todos/", views.TodoListView.as_view(), name="my_todos"),
    path("todo_details/<int:pk>/", views.TodoDetailView.as_view(), name="todo_details"),
    path("<int:pk>/update/", views.TodoUpdateView.as_view(), name="todo_update"),
    path("create/", views.TodoCreateView.as_view(), name="todo_create"),
    path('<int:pk>/delete/', views.TodoDeleteView.as_view(), name='todo_delete'),
    path("<int:pk>/done/", views.TodoDoneView.as_view(), name='todo_done'),
]

todo/models.py
from django.db import models

from users.models import User


class Todo(models.Model):
    title = models.CharField(max_length=100, null=False, blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField()
    is_done = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Title: {self.title}"

todo/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from todo.models import Todo
from django.views import View
from django.views.generic import (
    ListView,
    DetailView,
    UpdateView,
    CreateView,
    DeleteView
)


class TodoListView(ListView, LoginRequiredMixin):
    """
    This class will represent the todo's list view
    """
    model = Todo
    template_name = 'todo/todo_list.html'
    context_object_name = 'todos'
    paginate_by = 10

    def get_queryset(self):
        return Todo.objects.filter(user=self.request.user)


class TodoDetailView(DetailView, LoginRequiredMixin):
    """
    This class will represent the detail page of a single-Todo-object.
    """
    model = Todo
    context_object_name = 'todo'
    template_name = 'todo/todo_details.html'

    # we can also override the get_context_data method

    # def get_context_data(self, *args,**kwargs):
    #     context = super(TodoDetailView, self).get_context_data(*args, **kwargs)
    #
    #     context['title'] = context['object'].title
    #     return context


class TodoUpdateView(LoginRequiredMixin, UpdateView):
    """
    Class-based view for updating and existing Todo item.

    This view handles the modification of an existing Todo object via a form submission.
    It ensures that only authenticated users can update their own Todos.
    """
    model = Todo
    context_object_name = 'todo'
    fields = ['title', 'description']
    template_name = 'todo/todo_update.html'
    success_url = reverse_lazy('todo:my_todos')


class TodoCreateView(LoginRequiredMixin, CreateView):
    """
    Class-based view for creating new Todo items.

    This view handles the creation of new Todo objects via a form submission.
    It ensures that only authenticated users can create new Todos.
    """
    model = Todo
    template_name = "todo/todo_create.html"
    fields = ['title', 'description']
    context_object_name = 'todo'
    success_url = reverse_lazy('todo:my_todos')

    def form_valid(self, form):
        """
        Hook method to save the form data and set the current user as the creator.

        Overrides the default form_valid method to assign the current user to the form instance.
        """
        form.instance.user = self.request.user
        return super().form_valid(form)


class TodoDeleteView(DeleteView):
    """
    Class-based view for deleting a Todo item.

    This view handles the deletion of a Todo object identified by its primary key.
    """
    model = Todo
    context_object_name = 'todo'
    success_url = reverse_lazy('todo:my_todos')
    template_name = 'todo/todo_delete_confirm.html'


class TodoDoneView(View):
    """
    Class-based view for marking a Todo item as completed.

    This view sets the 'done' attribute of a Todo object to True, indicating completion.
    """

    def get(self, request, pk, *args, **kwargs):
        """
        Handles GET requests to mark a Todo item as completed.

        Retrieves the Todo item by its primary key, marks it as done, and redirects to the todos list.
        """
        todo = Todo.objects.get(pk=pk)
        todo.done = True
        return redirect("todo:my_todos")

templates/todo/todo_create.html
{% extends 'base.html' %}
{% block head %}
    <meta charset="UTF-8">
    <title>Title</title>
{% endblock %}
{% block content %}

    <h1>Creating a new task</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
    </form>
{% endblock %}

templates/todo/todo_delete_confirm.html
{% extends 'base.html' %}

{% block head %}
	<meta charset="UTF-8">
    <title>Title</title>
{% endblock %}

{% block content %}
<h1>Deleting {{ todo.title }}</h1>
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ todo.title }}"?</p>
        <button type="submit" class="btn btn-danger">Yes</button>
        <button type="button"><a href="{% url 'todo:my_todos' %}">No</a></button>
    </form>
{% endblock %}

templates/todo/todo_details.html
{% extends 'base.html' %}
{% block head %}
    <meta charset="UTF-8">
    <title>Title</title>
{% endblock head %}

{% block content %}

    <h1>{{ todo.title }}</h1>
    <p>{{ todo.description }}</p>
    <p>Created at  : {{ todo.created_at }}</p>
    <p>Last update: {{ todo.updated_at }}</p>

    <button class="btn btn-primary"><a href="{% url 'todo:todo_update' pk=todo.id %}" class="link-info">Update</a></button>
    <button class="btn btn-primary"><a href="{% url 'todo:todo_delete' pk=todo.id %}" class="link-info">Delete</a></button>
    <a href="{% url 'todo:todo_done' pk=todo.id %}" class="btn btn-info">Done</a>

{% endblock %}

templates/todo/todo_list.html
{% extends 'base.html' %}
{% block head %}
	<meta charset="UTF-8">
    <title>Title</title>

{% endblock %}
{% block content %}
    <h1>Welcome back {{ request.user.name }}</h1>
    <div>
        {% for todo in todos %}
            <h3>{{ todo.id }}. <a href="{% url 'todo:todo_details' pk=todo.id %}">{{ todo.title }}</a></h3>
            <p>{{ todo.created_at }}</p>

            <a href="{% url 'todo:todo_update' pk=todo.id %}" class="btn btn-primary">update</a>
            <a href="{% url 'todo:todo_delete' pk=todo.id %}" class="btn btn-danger">Delete</a>
            <a href="{% url 'todo:todo_done' pk=todo.id %}" class="btn btn-info">Done</a>
            <hr>
        {% endfor %}
    </div>
{% endblock content %}

templates/todo/todo_update.html
{% extends 'base.html' %}
{% block head %}
	<meta charset="UTF-8">
    <title>Title</title>
{% endblock %}
{% block content %}
    <h1>Editing {{ todo.title }}</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-info">Edit</button>
    </form>
{% endblock %}
